sudo: false
language: java
jdk:
- oraclejdk8
before_install:
- git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
- cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: UDGGR5Ae5bab+bzuin42jDEb9Al7RIGldTRv/c8SP42OYOmUHh0P4ShbK0qre+X+L8jbjfksQCPt7HWy1Y+oNSbD0F1darnqSHD7PDnO+nykXMuNgWDcAoRTAVMbk9S73eO6MAKNLm+jfwen0W/cN3YAVZO/xnSLxUJFBxZ4IngYC97zlD99pl97BElNhSockl0kpizFL+fUokCwSlaSyJGCDEbrR91ST0gTbqS4B49IuypUoFJJqhC5cAMnnOpS2wQgvzNXvUH3oV8Fk897/x6jAtngghJIuCmh+PWhMuW+PDCafOYqwroxlixO8iogaCOaqM0Q25rexITnUTk/Gyn6z5WtK2VgEKudPz46xv61wg1skfG9l5Xyss9wT3KszHIaCXuYThq795HQCZhGNjf1A25/v3H75I1K490bZxvLJne5a1U0Zlgi+6SxlKj/cBbbxp7ef3oYYQXXWGbcqiI5aQaV2s/qGVVnW056L3Ga7p+2N4xuANtl816mw5CXNNC3+1vFuiDjz3K2luOcqiA5eeYu2yNNtktpADGqaexiw/TQDXio4hYbV1/b4r7AZ37k6711VOVmiEV6hMXAQcNkdEj4IYkFid4hF/kjNYrVnRhvE3Etg29/l31kpt9MkDOamm2It6s8+joZ+LYFPi2pXZ1CJy2fooI+jbi5kB4=
  - secure: jO7uAZAizydElaZ/CstN28P/Zttcl+Cn7It+eqCpIU1OT/ECprqpnLxmmdu2+U0JTtqnboi9pRrdls3UMUK2XCxrjIMPMRFVhB/K9m1UOdK5x6MpkY4hPYfmmAlGRgtJW1ehfLMZSb/bejZnn2SiXTCPuoaDzSWgWawySRvkTNulcu3rDZoh7KLcnTAamEbNHo9jGrDwwcw6Xii9ZI8oHABGu+s3k4ooDFXcWlm9ZGu033SI6f8+AQHgCi8nhlR4OMySZET1RBXJ+U+zdWutxnY2OPq16HKzHMiZbLurq/LjQhk6YQFhGYnmtbSmHtd42UCkPXs2Sz76W1EzQIlR8ZUgZsvBZrJeVnrGxj33W1KtQbVDz0AXaxfKw3PVYSkUtUIIlhua/1T5BL2t32LNWjMkUWpR6SiBelCRCxOj7Ywk/6Oe+5lLjhJ2vILc+gP8kt/xT9N/pAjGsEyCG5Y5GVThr1LEpdr3NaiXlxZmJh2taAK+axOjg+Y9R5l0zQzFb3lfIlGsZf0Oj84W2JL02zxyNhsOaHkTQ4LvqVCrc2oxpyMd2ME4+OteYOJKJt+12OIZuieZ2WV2rOBincp5tCBpHHLOESYMCjDRdBCF8cJUNiN11OPmdE+YKu1KhBD+Zwyh/qR7QEtVWYawh7w4hLwooiGf/eKJbUQp7+3zOfA=
